import type { Metadata } from "next";
import { Azeret_Mono } from "next/font/google";
import "./globals.css";

const font = Azeret_Mono({ subsets: ["latin"], weight: "300" });

export const metadata: Metadata = {
  title: "Contatos Recall",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-Br">
      <body
        className={`${font.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
